### PR TITLE
Otn / ETH Model update for IETF 105

### PR DESCRIPTION
**Pull request by haomianzheng**
Issues to be solved: 

1. Cleanup current open issues in OTN topology and OTN tunnel. 
2. Separate out the layer 1 types to new draft, remove it from OTN tunnel draft and both OTN models import it; 
3. Update the OTN tunnel to be consistent with latest ietf-te; 
4. Update client-signal-yang, with clean up open issues; 
5. Update eth-topology-yang/eth-tunnel-yang to align with latest ietf-te-topology and ietf-te respectively.

### CODE REVIEW

**Comment by italobusi** [comment]
@haomianzheng : the ietf-otn-tunnel.yang was using the Windows EOL convention. I have converted it to UNIX in https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/35/commits/0bca92d0fd6d394b41119a4f798fcac12069eeb0

**Comment by italobusi** [comment]
@haomianzheng : Alos the ietf-otn-topology.tree was was using the Windows EOL convention. I have converted it to UNIX in https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/35/commits/6619d514a0c682266a9008ef931cee05f1ccd40e

**Comment by italobusi** [comment]
@haomianzheng : please compile the ietf-otn-tunnel.yang and upload the resulting ietf-otn-tunnel.tree

**Comment by haomianzheng** [comment]
> @haomianzheng : please compile the ietf-otn-tunnel.yang and upload the resulting ietf-otn-tunnel.tree

This is done, with slight changes in ietf-otn-tunnel.yang for bug fixing. 

See the tree at [https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/35/commits/08079c872bce245f3388131c1b292d1d977eee97](url) and the updated yang file at [https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/35/commits/8ca3d4be0e76ad18ae1d38b655a1d63df36a47e4](url)

**Pull request merged**
